// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: src/api/transport/rpc.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_Raft     Protocol = 0
	Protocol_Kademlia Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "Raft",
		1: "Kademlia",
	}
	Protocol_value = map[string]int32{
		"Raft":     0,
		"Kademlia": 1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_src_api_transport_rpc_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_src_api_transport_rpc_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_src_api_transport_rpc_proto_rawDescGZIP(), []int{0}
}

type Command int32

const (
	Command_PING             Command = 0
	Command_STORE            Command = 1
	Command_GET              Command = 2
	Command_FIND_NODE        Command = 3
	Command_FIND_VALUE       Command = 4
	Command_ACK              Command = 5
	Command_NODES            Command = 6
	Command_VALUE            Command = 7
	Command_REQUEST_VOTE     Command = 8
	Command_APPEND_ENTRIES   Command = 9
	Command_INSTALL_SNAPSHOT Command = 10
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0:  "PING",
		1:  "STORE",
		2:  "GET",
		3:  "FIND_NODE",
		4:  "FIND_VALUE",
		5:  "ACK",
		6:  "NODES",
		7:  "VALUE",
		8:  "REQUEST_VOTE",
		9:  "APPEND_ENTRIES",
		10: "INSTALL_SNAPSHOT",
	}
	Command_value = map[string]int32{
		"PING":             0,
		"STORE":            1,
		"GET":              2,
		"FIND_NODE":        3,
		"FIND_VALUE":       4,
		"ACK":              5,
		"NODES":            6,
		"VALUE":            7,
		"REQUEST_VOTE":     8,
		"APPEND_ENTRIES":   9,
		"INSTALL_SNAPSHOT": 10,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_src_api_transport_rpc_proto_enumTypes[1].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_src_api_transport_rpc_proto_enumTypes[1]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_src_api_transport_rpc_proto_rawDescGZIP(), []int{1}
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Time          int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_src_api_transport_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_transport_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_src_api_transport_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *NodeInfo) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type RPCT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       Command                `protobuf:"varint,1,opt,name=Command,proto3,enum=transport.Command" json:"Command,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=Protocol,proto3,enum=transport.Protocol" json:"Protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCT) Reset() {
	*x = RPCT{}
	mi := &file_src_api_transport_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCT) ProtoMessage() {}

func (x *RPCT) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_transport_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCT.ProtoReflect.Descriptor instead.
func (*RPCT) Descriptor() ([]byte, []int) {
	return file_src_api_transport_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RPCT) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_PING
}

func (x *RPCT) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_Raft
}

type RPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RPCT                  `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Sender        *NodeInfo              `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Key           []byte                 `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`             // kdht key
	Value         []byte                 `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`         // kdht value
	Nodes         []*NodeInfo            `protobuf:"bytes,6,rep,name=Nodes,proto3" json:"Nodes,omitempty"`         // k closest nodes field
	RequestID     string                 `protobuf:"bytes,7,opt,name=RequestID,proto3" json:"RequestID,omitempty"` // request correlation ID
	TraceID       string                 `protobuf:"bytes,8,opt,name=TraceID,proto3" json:"TraceID,omitempty"`     // distributed trace ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC) Reset() {
	*x = RPC{}
	mi := &file_src_api_transport_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC) ProtoMessage() {}

func (x *RPC) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_transport_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC.ProtoReflect.Descriptor instead.
func (*RPC) Descriptor() ([]byte, []int) {
	return file_src_api_transport_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RPC) GetMeta() *RPCT {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RPC) GetSender() *NodeInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *RPC) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RPC) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RPC) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RPC) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RPC) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *RPC) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

var File_src_api_transport_rpc_proto protoreflect.FileDescriptor

const file_src_api_transport_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1bsrc/api/transport/rpc.proto\x12\ttransport\"H\n" +
	"\bNodeInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x03R\x04time\"f\n" +
	"\x05RPC_t\x12,\n" +
	"\aCommand\x18\x01 \x01(\x0e2\x12.transport.CommandR\aCommand\x12/\n" +
	"\bProtocol\x18\x02 \x01(\x0e2\x13.transport.ProtocolR\bProtocol\"\xfd\x01\n" +
	"\x03RPC\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.transport.RPC_tR\x04Meta\x12+\n" +
	"\x06Sender\x18\x02 \x01(\v2\x13.transport.NodeInfoR\x06Sender\x12\x18\n" +
	"\aPayload\x18\x03 \x01(\fR\aPayload\x12\x10\n" +
	"\x03Key\x18\x04 \x01(\fR\x03Key\x12\x14\n" +
	"\x05Value\x18\x05 \x01(\fR\x05Value\x12)\n" +
	"\x05Nodes\x18\x06 \x03(\v2\x13.transport.NodeInfoR\x05Nodes\x12\x1c\n" +
	"\tRequestID\x18\a \x01(\tR\tRequestID\x12\x18\n" +
	"\aTraceID\x18\b \x01(\tR\aTraceID*\"\n" +
	"\bProtocol\x12\b\n" +
	"\x04Raft\x10\x00\x12\f\n" +
	"\bKademlia\x10\x01*\xa1\x01\n" +
	"\aCommand\x12\b\n" +
	"\x04PING\x10\x00\x12\t\n" +
	"\x05STORE\x10\x01\x12\a\n" +
	"\x03GET\x10\x02\x12\r\n" +
	"\tFIND_NODE\x10\x03\x12\x0e\n" +
	"\n" +
	"FIND_VALUE\x10\x04\x12\a\n" +
	"\x03ACK\x10\x05\x12\t\n" +
	"\x05NODES\x10\x06\x12\t\n" +
	"\x05VALUE\x10\a\x12\x10\n" +
	"\fREQUEST_VOTE\x10\b\x12\x12\n" +
	"\x0eAPPEND_ENTRIES\x10\t\x12\x14\n" +
	"\x10INSTALL_SNAPSHOT\x10\n" +
	"B0Z.github.com/danmuck/dps_files/src/api/transportb\x06proto3"

var (
	file_src_api_transport_rpc_proto_rawDescOnce sync.Once
	file_src_api_transport_rpc_proto_rawDescData []byte
)

func file_src_api_transport_rpc_proto_rawDescGZIP() []byte {
	file_src_api_transport_rpc_proto_rawDescOnce.Do(func() {
		file_src_api_transport_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_api_transport_rpc_proto_rawDesc), len(file_src_api_transport_rpc_proto_rawDesc)))
	})
	return file_src_api_transport_rpc_proto_rawDescData
}

var file_src_api_transport_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_api_transport_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_api_transport_rpc_proto_goTypes = []any{
	(Protocol)(0),    // 0: transport.Protocol
	(Command)(0),     // 1: transport.Command
	(*NodeInfo)(nil), // 2: transport.NodeInfo
	(*RPCT)(nil),     // 3: transport.RPC_t
	(*RPC)(nil),      // 4: transport.RPC
}
var file_src_api_transport_rpc_proto_depIdxs = []int32{
	1, // 0: transport.RPC_t.Command:type_name -> transport.Command
	0, // 1: transport.RPC_t.Protocol:type_name -> transport.Protocol
	3, // 2: transport.RPC.Meta:type_name -> transport.RPC_t
	2, // 3: transport.RPC.Sender:type_name -> transport.NodeInfo
	2, // 4: transport.RPC.Nodes:type_name -> transport.NodeInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_src_api_transport_rpc_proto_init() }
func file_src_api_transport_rpc_proto_init() {
	if File_src_api_transport_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_api_transport_rpc_proto_rawDesc), len(file_src_api_transport_rpc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_api_transport_rpc_proto_goTypes,
		DependencyIndexes: file_src_api_transport_rpc_proto_depIdxs,
		EnumInfos:         file_src_api_transport_rpc_proto_enumTypes,
		MessageInfos:      file_src_api_transport_rpc_proto_msgTypes,
	}.Build()
	File_src_api_transport_rpc_proto = out.File
	file_src_api_transport_rpc_proto_goTypes = nil
	file_src_api_transport_rpc_proto_depIdxs = nil
}
