// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: dps.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadChunk is sent in a client-streaming Upload RPC.
// The first message sets name and size; subsequent messages carry data only.
type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_dps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{0}
}

func (x *UploadChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadChunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_dps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *UploadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// DownloadRequest identifies a file by hash (preferred) or by name.
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_dps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *DownloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DataChunk is one piece of a server-streamed Download.
type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_dps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{3}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_dps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_dps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{5}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_dps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{6}
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	EntryType     string                 `protobuf:"bytes,4,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_dps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{7}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *FileEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileEntry           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_dps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type UploadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDirRequest) Reset() {
	*x = UploadDirRequest{}
	mi := &file_dps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDirRequest) ProtoMessage() {}

func (x *UploadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDirRequest.ProtoReflect.Descriptor instead.
func (*UploadDirRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{9}
}

func (x *UploadDirRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

type UploadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDirResponse) Reset() {
	*x = UploadDirResponse{}
	mi := &file_dps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDirResponse) ProtoMessage() {}

func (x *UploadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDirResponse.ProtoReflect.Descriptor instead.
func (*UploadDirResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{10}
}

func (x *UploadDirResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_dps_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{11}
}

func (x *ListDirRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_dps_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{12}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *DirEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DirEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_dps_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{13}
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_dps_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{14}
}

type VerifyError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    uint64                 `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyError) Reset() {
	*x = VerifyError{}
	mi := &file_dps_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyError) ProtoMessage() {}

func (x *VerifyError) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyError.ProtoReflect.Descriptor instead.
func (*VerifyError) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyError) GetChunkIndex() uint64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *VerifyError) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *VerifyError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*VerifyError         `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_dps_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyResponse) GetErrors() []*VerifyError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ExpireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireRequest) Reset() {
	*x = ExpireRequest{}
	mi := &file_dps_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireRequest) ProtoMessage() {}

func (x *ExpireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireRequest.ProtoReflect.Descriptor instead.
func (*ExpireRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{17}
}

type ExpireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int64                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireResponse) Reset() {
	*x = ExpireResponse{}
	mi := &file_dps_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireResponse) ProtoMessage() {}

func (x *ExpireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireResponse.ProtoReflect.Descriptor instead.
func (*ExpireResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{18}
}

func (x *ExpireResponse) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

// deep=true removes .kdht + metadata + cache; false removes .kdht only.
type CleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deep          bool                   `protobuf:"varint,1,opt,name=deep,proto3" json:"deep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	mi := &file_dps_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{19}
}

func (x *CleanRequest) GetDeep() bool {
	if x != nil {
		return x.Deep
	}
	return false
}

type CleanResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RemovedKdht     int64                  `protobuf:"varint,1,opt,name=removed_kdht,json=removedKdht,proto3" json:"removed_kdht,omitempty"`
	RemovedMetadata int64                  `protobuf:"varint,2,opt,name=removed_metadata,json=removedMetadata,proto3" json:"removed_metadata,omitempty"`
	RemovedCache    int64                  `protobuf:"varint,3,opt,name=removed_cache,json=removedCache,proto3" json:"removed_cache,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CleanResponse) Reset() {
	*x = CleanResponse{}
	mi := &file_dps_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanResponse) ProtoMessage() {}

func (x *CleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanResponse.ProtoReflect.Descriptor instead.
func (*CleanResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{20}
}

func (x *CleanResponse) GetRemovedKdht() int64 {
	if x != nil {
		return x.RemovedKdht
	}
	return 0
}

func (x *CleanResponse) GetRemovedMetadata() int64 {
	if x != nil {
		return x.RemovedMetadata
	}
	return 0
}

func (x *CleanResponse) GetRemovedCache() int64 {
	if x != nil {
		return x.RemovedCache
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_dps_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{21}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataBytes     uint64                 `protobuf:"varint,1,opt,name=data_bytes,json=dataBytes,proto3" json:"data_bytes,omitempty"`
	MetadataBytes uint64                 `protobuf:"varint,2,opt,name=metadata_bytes,json=metadataBytes,proto3" json:"metadata_bytes,omitempty"`
	CacheBytes    uint64                 `protobuf:"varint,3,opt,name=cache_bytes,json=cacheBytes,proto3" json:"cache_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FileCount     int64                  `protobuf:"varint,5,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_dps_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dps_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_dps_proto_rawDescGZIP(), []int{22}
}

func (x *StatsResponse) GetDataBytes() uint64 {
	if x != nil {
		return x.DataBytes
	}
	return 0
}

func (x *StatsResponse) GetMetadataBytes() uint64 {
	if x != nil {
		return x.MetadataBytes
	}
	return 0
}

func (x *StatsResponse) GetCacheBytes() uint64 {
	if x != nil {
		return x.CacheBytes
	}
	return 0
}

func (x *StatsResponse) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StatsResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

var File_dps_proto protoreflect.FileDescriptor

const file_dps_proto_rawDesc = "" +
	"\n" +
	"\tdps.proto\x12\x03dps\x1a\x1cgoogle/api/annotations.proto\"I\n" +
	"\vUploadChunk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"L\n" +
	"\x0eUploadResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"9\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1f\n" +
	"\tDataChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\x10\n" +
	"\x0eDeleteResponse\"\r\n" +
	"\vListRequest\"f\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x04 \x01(\tR\tentryType\"4\n" +
	"\fListResponse\x12$\n" +
	"\x05files\x18\x01 \x03(\v2\x0e.dps.FileEntryR\x05files\"/\n" +
	"\x10UploadDirRequest\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\"'\n" +
	"\x11UploadDirResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"n\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\":\n" +
	"\x0fListDirResponse\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.dps.DirEntryR\aentries\"\x0f\n" +
	"\rVerifyRequest\"a\n" +
	"\vVerifyError\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x04R\n" +
	"chunkIndex\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\":\n" +
	"\x0eVerifyResponse\x12(\n" +
	"\x06errors\x18\x01 \x03(\v2\x10.dps.VerifyErrorR\x06errors\"\x0f\n" +
	"\rExpireRequest\"*\n" +
	"\x0eExpireResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x03R\aremoved\"\"\n" +
	"\fCleanRequest\x12\x12\n" +
	"\x04deep\x18\x01 \x01(\bR\x04deep\"\x82\x01\n" +
	"\rCleanResponse\x12!\n" +
	"\fremoved_kdht\x18\x01 \x01(\x03R\vremovedKdht\x12)\n" +
	"\x10removed_metadata\x18\x02 \x01(\x03R\x0fremovedMetadata\x12#\n" +
	"\rremoved_cache\x18\x03 \x01(\x03R\fremovedCache\"\x0e\n" +
	"\fStatsRequest\"\xb6\x01\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"data_bytes\x18\x01 \x01(\x04R\tdataBytes\x12%\n" +
	"\x0emetadata_bytes\x18\x02 \x01(\x04R\rmetadataBytes\x12\x1f\n" +
	"\vcache_bytes\x18\x03 \x01(\x04R\n" +
	"cacheBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"file_count\x18\x05 \x01(\x03R\tfileCount2\x99\x06\n" +
	"\bDPSFiles\x12G\n" +
	"\x06Upload\x12\x10.dps.UploadChunk\x1a\x13.dps.UploadResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/files(\x01\x12e\n" +
	"\bDownload\x12\x14.dps.DownloadRequest\x1a\x0e.dps.DataChunk\"1\x82\xd3\xe4\x93\x02+Z\x17\x12\x15/v1/files/name/{name}\x12\x10/v1/files/{hash}0\x01\x12K\n" +
	"\x06Delete\x12\x12.dps.DeleteRequest\x1a\x13.dps.DeleteResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/files/{hash}\x12>\n" +
	"\x04List\x12\x10.dps.ListRequest\x1a\x11.dps.ListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/files\x12O\n" +
	"\tUploadDir\x12\x15.dps.UploadDirRequest\x1a\x16.dps.UploadDirResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/dirs\x12M\n" +
	"\aListDir\x12\x13.dps.ListDirRequest\x1a\x14.dps.ListDirResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/dirs/{hash}\x12K\n" +
	"\x06Verify\x12\x12.dps.VerifyRequest\x1a\x13.dps.VerifyResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/admin/verify\x12N\n" +
	"\x06Expire\x12\x12.dps.ExpireRequest\x1a\x13.dps.ExpireResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/admin/expire\x12J\n" +
	"\x05Clean\x12\x11.dps.CleanRequest\x1a\x12.dps.CleanResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/admin/clean\x12G\n" +
	"\x05Stats\x12\x11.dps.StatsRequest\x1a\x12.dps.StatsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admin/statsB)Z'github.com/danmuck/dps_files/src/api/pbb\x06proto3"

var (
	file_dps_proto_rawDescOnce sync.Once
	file_dps_proto_rawDescData []byte
)

func file_dps_proto_rawDescGZIP() []byte {
	file_dps_proto_rawDescOnce.Do(func() {
		file_dps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dps_proto_rawDesc), len(file_dps_proto_rawDesc)))
	})
	return file_dps_proto_rawDescData
}

var file_dps_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_dps_proto_goTypes = []any{
	(*UploadChunk)(nil),       // 0: dps.UploadChunk
	(*UploadResponse)(nil),    // 1: dps.UploadResponse
	(*DownloadRequest)(nil),   // 2: dps.DownloadRequest
	(*DataChunk)(nil),         // 3: dps.DataChunk
	(*DeleteRequest)(nil),     // 4: dps.DeleteRequest
	(*DeleteResponse)(nil),    // 5: dps.DeleteResponse
	(*ListRequest)(nil),       // 6: dps.ListRequest
	(*FileEntry)(nil),         // 7: dps.FileEntry
	(*ListResponse)(nil),      // 8: dps.ListResponse
	(*UploadDirRequest)(nil),  // 9: dps.UploadDirRequest
	(*UploadDirResponse)(nil), // 10: dps.UploadDirResponse
	(*ListDirRequest)(nil),    // 11: dps.ListDirRequest
	(*DirEntry)(nil),          // 12: dps.DirEntry
	(*ListDirResponse)(nil),   // 13: dps.ListDirResponse
	(*VerifyRequest)(nil),     // 14: dps.VerifyRequest
	(*VerifyError)(nil),       // 15: dps.VerifyError
	(*VerifyResponse)(nil),    // 16: dps.VerifyResponse
	(*ExpireRequest)(nil),     // 17: dps.ExpireRequest
	(*ExpireResponse)(nil),    // 18: dps.ExpireResponse
	(*CleanRequest)(nil),      // 19: dps.CleanRequest
	(*CleanResponse)(nil),     // 20: dps.CleanResponse
	(*StatsRequest)(nil),      // 21: dps.StatsRequest
	(*StatsResponse)(nil),     // 22: dps.StatsResponse
}
var file_dps_proto_depIdxs = []int32{
	7,  // 0: dps.ListResponse.files:type_name -> dps.FileEntry
	12, // 1: dps.ListDirResponse.entries:type_name -> dps.DirEntry
	15, // 2: dps.VerifyResponse.errors:type_name -> dps.VerifyError
	0,  // 3: dps.DPSFiles.Upload:input_type -> dps.UploadChunk
	2,  // 4: dps.DPSFiles.Download:input_type -> dps.DownloadRequest
	4,  // 5: dps.DPSFiles.Delete:input_type -> dps.DeleteRequest
	6,  // 6: dps.DPSFiles.List:input_type -> dps.ListRequest
	9,  // 7: dps.DPSFiles.UploadDir:input_type -> dps.UploadDirRequest
	11, // 8: dps.DPSFiles.ListDir:input_type -> dps.ListDirRequest
	14, // 9: dps.DPSFiles.Verify:input_type -> dps.VerifyRequest
	17, // 10: dps.DPSFiles.Expire:input_type -> dps.ExpireRequest
	19, // 11: dps.DPSFiles.Clean:input_type -> dps.CleanRequest
	21, // 12: dps.DPSFiles.Stats:input_type -> dps.StatsRequest
	1,  // 13: dps.DPSFiles.Upload:output_type -> dps.UploadResponse
	3,  // 14: dps.DPSFiles.Download:output_type -> dps.DataChunk
	5,  // 15: dps.DPSFiles.Delete:output_type -> dps.DeleteResponse
	8,  // 16: dps.DPSFiles.List:output_type -> dps.ListResponse
	10, // 17: dps.DPSFiles.UploadDir:output_type -> dps.UploadDirResponse
	13, // 18: dps.DPSFiles.ListDir:output_type -> dps.ListDirResponse
	16, // 19: dps.DPSFiles.Verify:output_type -> dps.VerifyResponse
	18, // 20: dps.DPSFiles.Expire:output_type -> dps.ExpireResponse
	20, // 21: dps.DPSFiles.Clean:output_type -> dps.CleanResponse
	22, // 22: dps.DPSFiles.Stats:output_type -> dps.StatsResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_dps_proto_init() }
func file_dps_proto_init() {
	if File_dps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dps_proto_rawDesc), len(file_dps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dps_proto_goTypes,
		DependencyIndexes: file_dps_proto_depIdxs,
		MessageInfos:      file_dps_proto_msgTypes,
	}.Build()
	File_dps_proto = out.File
	file_dps_proto_goTypes = nil
	file_dps_proto_depIdxs = nil
}
