// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: dps.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DPSFiles_Upload_FullMethodName    = "/dps.DPSFiles/Upload"
	DPSFiles_Download_FullMethodName  = "/dps.DPSFiles/Download"
	DPSFiles_Delete_FullMethodName    = "/dps.DPSFiles/Delete"
	DPSFiles_List_FullMethodName      = "/dps.DPSFiles/List"
	DPSFiles_UploadDir_FullMethodName = "/dps.DPSFiles/UploadDir"
	DPSFiles_ListDir_FullMethodName   = "/dps.DPSFiles/ListDir"
)

// DPSFilesClient is the client API for DPSFiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DPSFilesClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadResponse], error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	UploadDir(ctx context.Context, in *UploadDirRequest, opts ...grpc.CallOption) (*UploadDirResponse, error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
}

type dPSFilesClient struct {
	cc grpc.ClientConnInterface
}

func NewDPSFilesClient(cc grpc.ClientConnInterface) DPSFilesClient {
	return &dPSFilesClient{cc}
}

func (c *dPSFilesClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DPSFiles_ServiceDesc.Streams[0], DPSFiles_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DPSFiles_UploadClient = grpc.ClientStreamingClient[UploadChunk, UploadResponse]

func (c *dPSFilesClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DPSFiles_ServiceDesc.Streams[1], DPSFiles_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DPSFiles_DownloadClient = grpc.ServerStreamingClient[DataChunk]

func (c *dPSFilesClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, DPSFiles_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPSFilesClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, DPSFiles_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPSFilesClient) UploadDir(ctx context.Context, in *UploadDirRequest, opts ...grpc.CallOption) (*UploadDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDirResponse)
	err := c.cc.Invoke(ctx, DPSFiles_UploadDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPSFilesClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, DPSFiles_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DPSFilesServer is the server API for DPSFiles service.
// All implementations must embed UnimplementedDPSFilesServer
// for forward compatibility.
type DPSFilesServer interface {
	Upload(grpc.ClientStreamingServer[UploadChunk, UploadResponse]) error
	Download(*DownloadRequest, grpc.ServerStreamingServer[DataChunk]) error
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	UploadDir(context.Context, *UploadDirRequest) (*UploadDirResponse, error)
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	mustEmbedUnimplementedDPSFilesServer()
}

// UnimplementedDPSFilesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDPSFilesServer struct{}

func (UnimplementedDPSFilesServer) Upload(grpc.ClientStreamingServer[UploadChunk, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedDPSFilesServer) Download(*DownloadRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedDPSFilesServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDPSFilesServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDPSFilesServer) UploadDir(context.Context, *UploadDirRequest) (*UploadDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadDir not implemented")
}
func (UnimplementedDPSFilesServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedDPSFilesServer) mustEmbedUnimplementedDPSFilesServer() {}
func (UnimplementedDPSFilesServer) testEmbeddedByValue()                  {}

// UnsafeDPSFilesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DPSFilesServer will
// result in compilation errors.
type UnsafeDPSFilesServer interface {
	mustEmbedUnimplementedDPSFilesServer()
}

func RegisterDPSFilesServer(s grpc.ServiceRegistrar, srv DPSFilesServer) {
	// If the following call panics, it indicates UnimplementedDPSFilesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DPSFiles_ServiceDesc, srv)
}

func _DPSFiles_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DPSFilesServer).Upload(&grpc.GenericServerStream[UploadChunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DPSFiles_UploadServer = grpc.ClientStreamingServer[UploadChunk, UploadResponse]

func _DPSFiles_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DPSFilesServer).Download(m, &grpc.GenericServerStream[DownloadRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DPSFiles_DownloadServer = grpc.ServerStreamingServer[DataChunk]

func _DPSFiles_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPSFilesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPSFiles_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPSFilesServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPSFiles_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPSFilesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPSFiles_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPSFilesServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPSFiles_UploadDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPSFilesServer).UploadDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPSFiles_UploadDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPSFilesServer).UploadDir(ctx, req.(*UploadDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPSFiles_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPSFilesServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPSFiles_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPSFilesServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DPSFiles_ServiceDesc is the grpc.ServiceDesc for DPSFiles service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DPSFiles_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dps.DPSFiles",
	HandlerType: (*DPSFilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _DPSFiles_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DPSFiles_List_Handler,
		},
		{
			MethodName: "UploadDir",
			Handler:    _DPSFiles_UploadDir_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _DPSFiles_ListDir_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _DPSFiles_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _DPSFiles_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dps.proto",
}
